# https://taskfile.dev/#/installation
version: 3

# env - dotenv, global, local
dotenv: ['.env']

# tasks
tasks:
  all:
    cmds:
      - task: build
      - task: docs

  cmake-format:
    - cmake-format --in-place
      ./index.cmake
      ./cmake/*.cmake
      ./lib/index.cmake
      ./app/index.cmake
      ./tests/index.cmake

  clang-format:
    - clang-format -i ./lib/*.cc ./app/*.cc --style=file

  build:
    - cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Debug #-G "Ninja Multi-Config"
    - cmake --build build

  install:
    - cd ./build && make install # ninja install

  docs:
    - cmake --build build --target doxygen-docs
    - cp -r ./build/html ./docs

  tests:
    - cmake --build build --target ctest

  clean:
    - rm -rf build docs



